PhoneBookHumanGroupPL/Components/TopMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBookHumanGroupBL.InterfacesOfManagers;
using PhoneBookHumanGroupEL.ViewModels;

namespace PhoneBookHumanGroupPL.Components
{
    public class TopMenuViewComponent: ViewComponent
    {
        private readonly IMemberManager _memberManager;

        public TopMenuViewComponent(IMemberManager memberManager)
        {
            _memberManager = memberManager;
        }

        public IViewComponentResult Invoke()
        {
            try
            {
                var loggedInUserEmail = HttpContext.User.Identity.Name;
                if (!string.IsNullOrEmpty(loggedInUserEmail))
                {
                    var loggedInUser = _memberManager.GetByCondition(x => x.Email.ToLower() == loggedInUserEmail.ToLower()).Data;
                    //return View(loggedInUserEmail);
                    //1. yol 1. yöntemi
                    //return View(null, loggedInUser);
                    //1. yol 2. yöntemi
                    // return View("Default", loggedInUser);

                    //2. yol
                    //return View<MemberVM>(loggedInUser);


                    //ViewComponentiçinde return View() yaptığımız yerde defaulttan farklı bir sayfaya gönderme örneği yapalım.
                     return View("TopMenuTheme", loggedInUser);

                }

                return View("TopMenuTheme", new MemberVM());
            }
            catch (Exception ex)
            {
                return View("TopMenuTheme", new MemberVM());
            }
        }
    }
}

PhoneBookHumanGroupPL/Views/Shared/PartialFooter.cshtml
<p>Burası  partialdan geldi</p>
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - PhoneBookHumanGroupPL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

PhoneBookHumanGroupPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhoneBookHumanGroupPL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhoneBookHumanGroupPL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @await Component.InvokeAsync("TopMenu")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  <partial name="PartialFooter"></partial>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PhoneBookHumanGroupPL/Views/Shared/_LayoutPhoneBookTheme.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Seomark</title>

    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/seomark/css/bootstrap.css" />
    <!-- fonts awesome style -->
    <link href="~/seomark/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/seomark/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/seomark/css/responsive.css" rel="stylesheet" />
</head>

<body class="sub_page">
    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            @await Component.InvokeAsync("TopMenu")
        </header>
        <!-- end header section -->
    </div>


    <!-- we do section -->

    <section class="wedo_section layout_padding">
        <div class="container">
            <div class="heading_container">
               @RenderBody()
        </div>
    </section>

    <!-- end we do section -->
    <!-- info section -->

    <section class="info_section layout_padding2">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="info_contact">
                        <h4>
                            Address
                        </h4>
                        <div class="contact_link_box">
                            <a href="">
                                <i class="fa fa-map-marker" aria-hidden="true"></i>
                                <span>
                                    Location
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-phone" aria-hidden="true"></i>
                                <span>
                                    Call +01 1234567890
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                                <span>
                                    demo@gmail.com
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="info_social">
                        <a href="">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="info_link_box">
                        <h4>
                            Links
                        </h4>
                        <div class="info_links">
                            <a class="" href="index.html">
                                <img src="~/seomark/images/nav-bullet.png" alt="">
                                Home
                            </a>
                            <a class="" href="about.html">
                                <img src="~/seomark/images/nav-bullet.png" alt="">
                                About
                            </a>
                            <a class="active" href="service.html">
                                <img src="~/seomark/images/nav-bullet.png" alt="">
                                Services
                            </a>
                            <a class="" href="testimonial.html">
                                <img src="~/seomark/images/nav-bullet.png" alt="">
                                Testimonial
                            </a>
                            <a class="" href="news.html">
                                <img src="~/seomark/images/nav-bullet.png" alt="">
                                Latest News
                            </a>
                            <a class="" href="contact.html">
                                <img src="~/seomark/images/nav-bullet.png" alt="">
                                Contact Us
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="info_detail">
                        <h4>
                            Info
                        </h4>
                        <p>
                            necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful
                        </p>
                    </div>
                </div>
                <div class="col-md-3">
                    <h4>
                        Subscribe
                    </h4>
                    <form action="#">
                        <input type="text" placeholder="Enter email" />
                        <button type="submit">
                            Subscribe
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <!-- end info section -->
    <!-- footer section -->
    <footer class="footer_section">
        <div class="container">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <p>
                        &copy; <span id="displayYear"></span> All Rights Reserved. Design by
                        <a href="https://html.design/">Free Html Templates</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer section -->

    <script src="~/seomark/js/jquery-3.4.1.min.js"></script>
    <script src="~/seomark/js/bootstrap.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <script src="~/seomark/js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
    <!-- End Google Map -->
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>